### ISSUE TITLE
README中的样例出错

### ISSUE THREAD

**Issue by SeeFlowerX** [yanyongyu/JceStruct#2]
```python
python -m jce 1f2e3d4c5b6a79
```

版本是 JceStruct 0.1.2

报错信息如下

```bash
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\14215\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Miniconda3\envs\14215\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Miniconda3\envs\14215\lib\site-packages\jce\__main__.py", line 13, in <module>
    result = JceDecoder.decode_bytes(bytes.fromhex(args.encoded))
  File "C:\ProgramData\Miniconda3\envs\14215\lib\site-packages\jce\types.py", line 186, in decode_bytes
    jce_id, data, data_length = cls.decode_single(
  File "C:\ProgramData\Miniconda3\envs\14215\lib\site-packages\jce\types.py", line 173, in decode_single
    raise ValueError(f"Unknown JceType for id {type_}")
ValueError: Unknown JceType for id 15
```

**Comment by yanyongyu** [comment]
readme里的数据是样例啊，你替换成你自己的数据hex格式字符串

**Comment by SeeFlowerX** [comment]
[q.txt](https://github.com/yanyongyu/JceStruct/files/6607884/q.txt)

感谢回答，是我理解不到位。不过手上的数据还是没法直接解析，代码如下

```python
from jce import JceDecoder
from pathlib import Path
data = Path(r"q.txt").read_bytes()
plain = JceDecoder.decode_bytes(data)
print(plain)
```
报错如下

```bash
Traceback (most recent call last):
  File "qq\test.py", line 8, in <module>
    plain = JceDecoder.decode_bytes(data)
  File "C:\Users\Administrator\Documents\qq\jce\types.py", line 186, in decode_bytes
    jce_id, data, data_length = cls.decode_single(
  File "C:\Users\Administrator\Documents\qq\jce\types.py", line 174, in decode_single
    data, data_length = JceType.from_bytes(jce_byte[head_length:], **extra)
  File "C:\Users\Administrator\Documents\qq\jce\types.py", line 444, in from_bytes
    return data[4:length + 4].decode(), length + 4
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 58: invalid start byte
```

还请指点

**Comment by yanyongyu** [comment]
这应该是你的string编码问题（

这里使用的是utf-8

**Comment by SeeFlowerX** [comment]
这里有一个gzip头，可能jce的内容应该需要从这里解压出来，我再看看。

![image](https://user-images.githubusercontent.com/70688581/120999520-caca4f00-c7bb-11eb-8321-4a99e26a5359.png)

**Comment by SeeFlowerX** [comment]
确实如上所述，解压后可以看到大部分明文，不过依然无法使用本项目进行解析。

![image](https://user-images.githubusercontent.com/70688581/121000428-c94d5680-c7bc-11eb-96ec-a706a6fb28be.png)


样本：
[q_decompressed.txt](https://github.com/yanyongyu/JceStruct/files/6608002/q_decompressed.txt)

报错如下

```bash
Traceback (most recent call last):
  File "qq\test.py", line 8, in <module>
    plain = JceDecoder.decode_bytes(data)
  File "C:\Users\Administrator\Documents\qq\jce\types.py", line 186, in decode_bytes 
    jce_id, data, data_length = cls.decode_single(
  File "C:\Users\Administrator\Documents\qq\jce\types.py", line 174, in decode_single
    data, data_length = JceType.from_bytes(jce_byte[head_length:], **extra)
  File "C:\Users\Administrator\Documents\qq\jce\types.py", line 466, in from_bytes   
    _, key, key_length = cls.__jce_decoder__.decode_single(
  File "C:\Users\Administrator\Documents\qq\jce\types.py", line 174, in decode_single
    data, data_length = JceType.from_bytes(jce_byte[head_length:], **extra)
  File "C:\Users\Administrator\Documents\qq\jce\types.py", line 468, in from_bytes
    _, value, value_length = cls.__jce_decoder__.decode_single(
  File "C:\Users\Administrator\Documents\qq\jce\types.py", line 174, in decode_single
    data, data_length = JceType.from_bytes(jce_byte[head_length:], **extra)
  File "C:\Users\Administrator\Documents\qq\jce\types.py", line 468, in from_bytes
    _, value, value_length = cls.__jce_decoder__.decode_single(
  File "C:\Users\Administrator\Documents\qq\jce\types.py", line 174, in decode_single
    data, data_length = JceType.from_bytes(jce_byte[head_length:], **extra)
  File "C:\Users\Administrator\Documents\qq\jce\types.py", line 575, in from_bytes
    return JceStruct.from_bytes(data, **extra)
  File "C:\Users\Administrator\Documents\qq\jce\types.py", line 716, in from_bytes
    jce_id, decoded, data_length = cls.__jce_decoder__.decode_single(
  File "C:\Users\Administrator\Documents\qq\jce\types.py", line 174, in decode_single
    data, data_length = JceType.from_bytes(jce_byte[head_length:], **extra)
  File "C:\Users\Administrator\Documents\qq\jce\types.py", line 535, in from_bytes
    list_count = INT32.validate(list_count)
  File "C:\Users\Administrator\Documents\qq\jce\types.py", line 332, in validate
    raise TypeError(f"Invalid value type: {type(v)}")
TypeError: Invalid value type: <class 'jce.types.FLOAT'>
```

**Comment by yanyongyu** [comment]
你可能需要确认一下是否为jce数据，我似乎在数据中看见了protobuf

**Comment by SeeFlowerX** [comment]
似乎确有此种可能，谢谢回复。

**Comment by SeeFlowerX** [comment]
追加补充，上面的样例数据来自于一个请求的返回结果，是protobuf，不过它的请求数据是Jce

感谢dalao的项目~

![image](https://user-images.githubusercontent.com/70688581/122018726-b4dd0f80-cdf5-11eb-815a-8cce87180eac.png)

**Comment by SeeFlowerX** [comment]
追加补充2，后面经过分析，确定请求体也是protobuf格式，如图所示（结合上一楼可以对比）

![image](https://user-images.githubusercontent.com/70688581/122039179-f7f4ae00-ce08-11eb-9b2e-9a33d50f28c7.png)

换句话说，Jce本质上是protobuf的变体，或者说它们是互通的

基于这个思路，我再次测试了前面的`q_decompressed.txt`样本（测试时请删除前18字节），发现本项目JceStruct解析结果居然比proto还原出来的数据更多...

具体参见下图，

![image](https://user-images.githubusercontent.com/70688581/122039859-aef12980-ce09-11eb-9844-e1aab6f02d58.png)

可以看到`1000 <chunk> = message:`后面这部分数据没有体现在proto中，这是因为原始的代码中也确实没有对它操作

![](https://imgur.com/a/nPBGihD)

通过进一步分析APP（腾讯视频）的反编译代码，并没有发现有tag=1000能和这里对应的结果

好在本项目可以解析出来，有此辅助，可以进一步完善proto了

**Comment by SeeFlowerX** [comment]
我对于Jce几乎没有什么了解，但是根据以上结果来看，Jce**几乎就是**protobuf......

另外追加一点测试

样本 [q_decompressed_jce_pb.txt](https://github.com/yanyongyu/JceStruct/files/6655047/q_decompressed_jce_pb.txt)

## protoc解码

安装以下包

```bash
pip install grpcio
pip install grpcio-tools
```

执行命令

`python -m grpc_tools.protoc --decode_raw < q_decompressed_jce_pb.txt`

![image](https://user-images.githubusercontent.com/70688581/122042483-c978d200-ce0c-11eb-8bc7-cdc063b3195a.png)

## JceStruct解码

```python
from protobuf_inspector.types import StandardParser
parser = StandardParser()
with open(r'q_decompressed_jce_pb.txt', 'rb') as fh:
   output = parser.parse_message(fh, "message")
print(output)
```

![image](https://user-images.githubusercontent.com/70688581/122042501-ced61c80-ce0c-11eb-8b41-8d1d6fcd59b7.png)

**Comment by yanyongyu** [comment]
你下面那个并不是jce解码啊

**Comment by SeeFlowerX** [comment]
这几天看迷糊了...

感谢回复，不然我还在纳闷(
